### PR TITLE
adding smartfin

### PR DESCRIPTION
**Pull request by lucmehl**
@kwilcox , we need to add the help documentation to smartfin portal, it currently directs to AOOS help docs.

I created a page within `partner_content` for specific Smartfin info, but I'm not sure what that means, where it will show up, if at all.

Please let me know if there is a way to preview this before merging.

Once I see the result I will finish the customization (figures, exclusions, etc.)

### CODE REVIEW

**Comment by kwilcox** [comment]
I'm passing this along the top of the key to @shane-axiom

**Comment by srstsavage** [comment]
@lucmehl Apparently I was watching the jumbotron and the ball bounced into the stands.

We're not currently set up to deploy previewable builds of branches, but I did update the master branch and added a note about previewing to the [README.md](https://github.com/axiom-data-science/portal-docs/tree/add-smartfin#previewing). (I rebased this branch as well).

When you're back you can preview locally using:

```
docker build -t portal-docs --build-arg PORTAL=smartfin .
docker run --rm -p 8888:8888 portal-docs
```

And opening <http://localhost:8888>.

**Comment by srstsavage** [comment]
Also the data access page you created shows up for me, so that's good.

**Comment by srstsavage** [comment]
@lucmehl Any reason not to merge this?

**Comment by lucmehl** [comment]
Sorry Shane, this is far enough back that I don't really remember the
effort.

We do need to make public documentation for smartfin somewhere. I assumed
this is the right place to do that. But @Kyle Wilcox
<kyle@axiomdatascience.com> is the one with the vision.

**Pull request closed without merging**
