### PR TITLE
Trying to merge chunks with master

### PR DESCRIPTION
**Pull request by gilltron**
@shane-axiom: per BJ, I've restructured the portal docs into smaller chunks in the chunks branch. Now I'd like to make it so the portal docs have the new structure. I think that's what this pull request will do but I lack confidence in my gitability. Please review and advise.

Thank you!

### CODE REVIEW

**Comment by gilltron** [comment]
Or maybe @kwilcox could help review?

**Comment by srstsavage** [comment]
@gilltron It looks like there are conflicts in a few files (see below). Are you confident in trying to resolve those, or should I?

**Comment by gilltron** [comment]
@shane-axiom Yeah, that's where I need help. I tried looking at the conflicts but don't have experience comparing branches from the command line.

I realize this is a pain, though, since I made the edits. I can try merging locally and see how it goes.

**Comment by gilltron** [comment]
@shane-axiom Let me know if you get to this. I'm working on it locally and it's making sense so far. Hopefully I can just do it.

https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/

**Pull request merged**
